# Generated by Django 5.0.2 on 2024-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Comprador/a',
                'verbose_name_plural': 'Compradores/as',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=60)),
                ('precio', models.FloatField()),
            ],
            options={
                'ordering': ['nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('tel_contacto', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vendedor/a',
                'verbose_name_plural': 'Vendedores/as',
                'ordering': ['apellido'],
            },
        ),
    ]
